### ISSUE TITLE
BOE panel may have more suitable firmware

### ISSUE THREAD

**Issue by 12345XuXin54321** [lujianhua/xiaomi-elish-firmware#1]
My xiaomi pad 5 pro is use BOE panel, and if it using this nt36523.bin (sha1sum is 78791cff666d992d6d55ac62230fc74e68118b3b) it will receive a floral screen. If use [this firmware](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/elish-r-oss/firmware/novatek_nt36523_fw02.bin.ihex) (sha1sum is 874e4070d9bd8b9f961c33e92d0a82a67fa92c30) it will display normally.

**Comment by lujianhua** [comment]
You can open a PR to add this firmware with boe-nt36523.bin named
